"""Knowledge domains — fields of intellectual discipline."""

from graph.knowledge_entities import Domain


def create_domains() -> list[Domain]:
    return [
        # Top-level domains
        Domain(id="domain-philosophy", name="Philosophy",
               description="The study of fundamental questions about existence, knowledge, values, reason, mind, and language."),
        Domain(id="domain-theology", name="Theology",
               description="Systematic study of the divine, religious belief, and the nature of God."),
        Domain(id="domain-mathematics", name="Mathematics",
               description="The study of quantity, structure, space, and change through abstract reasoning."),
        Domain(id="domain-psychology", name="Psychology",
               description="The scientific study of mind and behavior."),
        Domain(id="domain-science", name="Natural Science",
               description="Systematic study of the natural world through observation and experiment."),
        Domain(id="domain-social-science", name="Social Science",
               description="Study of human society and social relationships."),
        Domain(id="domain-arts", name="Arts & Literature",
               description="Creative and interpretive works including literature, poetry, visual arts."),
        Domain(id="domain-computer-science", name="Computer Science",
               description="Study of computation, information processing, and automated reasoning."),

        # Philosophy sub-domains
        Domain(id="domain-epistemology", name="Epistemology",
               description="Branch of philosophy concerned with the nature, scope, and limits of knowledge.",
               parent_domain_id="domain-philosophy"),
        Domain(id="domain-metaphysics", name="Metaphysics",
               description="Branch of philosophy examining the fundamental nature of reality.",
               parent_domain_id="domain-philosophy"),
        Domain(id="domain-ethics", name="Ethics",
               description="Branch of philosophy dealing with moral principles and right conduct.",
               parent_domain_id="domain-philosophy"),
        Domain(id="domain-political-philosophy", name="Political Philosophy",
               description="Study of fundamental questions about government, politics, liberty, justice.",
               parent_domain_id="domain-philosophy"),
        Domain(id="domain-aesthetics", name="Aesthetics",
               description="Branch of philosophy dealing with the nature of beauty and taste.",
               parent_domain_id="domain-philosophy"),
        Domain(id="domain-logic", name="Logic",
               description="Study of valid reasoning and argumentation.",
               parent_domain_id="domain-philosophy"),
        Domain(id="domain-phenomenology", name="Phenomenology",
               description="Study of structures of conscious experience from the first-person perspective.",
               parent_domain_id="domain-philosophy"),
        Domain(id="domain-philosophy-of-science", name="Philosophy of Science",
               description="Study of the foundations, methods, and implications of science.",
               parent_domain_id="domain-philosophy"),
        Domain(id="domain-philosophy-of-mind", name="Philosophy of Mind",
               description="Study of the nature of mind, mental events, consciousness, and their relationship to the body.",
               parent_domain_id="domain-philosophy"),

        # Theology sub-domains
        Domain(id="domain-systematic-theology", name="Systematic Theology",
               description="Formulation of doctrine from biblical texts and the history of theology.",
               parent_domain_id="domain-theology"),
        Domain(id="domain-mysticism", name="Mysticism",
               description="Practice of religious ecstasies, altered states of consciousness, and direct experience of the divine.",
               parent_domain_id="domain-theology"),
        Domain(id="domain-biblical-studies", name="Biblical Studies",
               description="Academic study of the Hebrew Bible and New Testament.",
               parent_domain_id="domain-theology"),
        Domain(id="domain-comparative-religion", name="Comparative Religion",
               description="Systematic comparison of doctrines and practices of world religions.",
               parent_domain_id="domain-theology"),

        # Psychology sub-domains
        Domain(id="domain-psychoanalysis", name="Psychoanalysis",
               description="Clinical method and theory of the unconscious mind.",
               parent_domain_id="domain-psychology"),
        Domain(id="domain-cognitive-psychology", name="Cognitive Psychology",
               description="Study of mental processes including attention, language, memory, perception, and thinking.",
               parent_domain_id="domain-psychology"),
        Domain(id="domain-neuroscience", name="Neuroscience",
               description="Study of the nervous system and brain.",
               parent_domain_id="domain-psychology"),
        Domain(id="domain-clinical-psychology", name="Clinical Psychology",
               description="Assessment and treatment of mental illness and psychological problems.",
               parent_domain_id="domain-psychology"),

        # Mathematics sub-domains
        Domain(id="domain-topology", name="Topology",
               description="Study of geometric properties preserved under continuous deformations.",
               parent_domain_id="domain-mathematics"),
        Domain(id="domain-statistics", name="Statistics",
               description="Study of data collection, analysis, interpretation, and presentation.",
               parent_domain_id="domain-mathematics"),
        Domain(id="domain-mathematical-logic", name="Mathematical Logic",
               description="Study of formal logic within mathematics, including model theory and proof theory.",
               parent_domain_id="domain-mathematics"),

        # Science sub-domains
        Domain(id="domain-complexity-science", name="Complexity Science",
               description="Study of complex adaptive systems, emergence, self-organization, and nonlinear dynamics.",
               parent_domain_id="domain-science"),
        Domain(id="domain-physics", name="Physics",
               description="Study of matter, energy, and the fundamental forces of nature.",
               parent_domain_id="domain-science"),
        Domain(id="domain-information-theory", name="Information Theory",
               description="Mathematical study of quantification, storage, and communication of information.",
               parent_domain_id="domain-science"),

        # CS sub-domains
        Domain(id="domain-ai-ml", name="Artificial Intelligence & Machine Learning",
               description="Study and development of intelligent agents and learning algorithms.",
               parent_domain_id="domain-computer-science"),
        Domain(id="domain-causal-inference", name="Causal Inference",
               description="Statistical and graphical methods for determining cause-and-effect relationships.",
               parent_domain_id="domain-statistics"),

        # Social Science sub-domains
        Domain(id="domain-sociology", name="Sociology",
               description="Study of social behavior, society, patterns of social relationships, and culture.",
               parent_domain_id="domain-social-science"),
        Domain(id="domain-economics", name="Economics",
               description="Study of production, distribution, and consumption of goods and services.",
               parent_domain_id="domain-social-science"),
        Domain(id="domain-history", name="History",
               description="Study and interpretation of past events.",
               parent_domain_id="domain-social-science"),
        Domain(id="domain-anthropology", name="Anthropology",
               description="Study of human societies, cultures, and their development.",
               parent_domain_id="domain-social-science"),

        # Arts sub-domains
        Domain(id="domain-literary-theory", name="Literary Theory",
               description="Systematic study of the nature of literature and methods for analyzing it.",
               parent_domain_id="domain-arts"),
        Domain(id="domain-rhetoric", name="Rhetoric",
               description="Art of effective or persuasive speaking or writing.",
               parent_domain_id="domain-arts"),
    ]
