"""Historical periods and epochs."""

from graph.knowledge_entities import HistoricalPeriod, ManuscriptReference


def create_historical_periods() -> list[HistoricalPeriod]:
    return [
        HistoricalPeriod(
            id="period-axial-age",
            name="Axial Age",
            start_year=-800, end_year=-200,
            description="Period when foundational philosophical and religious traditions emerged independently across civilizations: Greek philosophy, Hebrew prophecy, Buddhism, Confucianism, Zoroastrianism.",
            dominant_paradigm="Emergence of self-reflective consciousness across civilizations",
            key_events=["Greek philosophy emerges", "Hebrew prophetic tradition crystallizes", "Buddha's enlightenment", "Confucius teaches", "Zoroaster's reforms"],
            manuscript_refs=[ManuscriptReference(chapter=13, part="part3-metaphysics", notes="Consciousness becoming self-aware across civilizations")],
        ),
        HistoricalPeriod(
            id="period-classical-antiquity",
            name="Classical Antiquity",
            start_year=-500, end_year=500,
            description="Era of Greek and Roman civilization, including the flowering of philosophy, democracy, and eventually the rise of Christianity.",
            dominant_paradigm="Greek rationalism and Roman institutional order",
            key_events=["Athenian democracy", "Alexander's conquests", "Roman Republic/Empire", "Rise of Christianity", "Fall of Western Rome"],
        ),
        HistoricalPeriod(
            id="period-late-antiquity",
            name="Late Antiquity",
            start_year=200, end_year=700,
            description="Transformation of the ancient world: rise of Christianity, Islamic civilization emerges, patristic theology crystallizes.",
            key_events=["Council of Nicaea (325)", "Augustine writes", "Fall of Rome (476)", "Muhammad's revelation (610)", "Islamic expansion"],
        ),
        HistoricalPeriod(
            id="period-islamic-golden-age",
            name="Islamic Golden Age",
            start_year=750, end_year=1258,
            description="Period of cultural, economic, and scientific flourishing in the Islamic world. Bayt al-Hikma (House of Wisdom) as Republic of Letters ancestor.",
            dominant_paradigm="Synthesis of Greek, Persian, Indian, and Arab knowledge",
            key_events=["Bayt al-Hikma founded", "Al-Khwarizmi invents algebra", "Ibn Sina's Canon", "Al-Ghazali's critique", "Ibn Arabi writes"],
            manuscript_refs=[ManuscriptReference(chapter=18, part="part3-metaphysics", notes="Arab-Islamic ancestor of Republic of Letters")],
        ),
        HistoricalPeriod(
            id="period-medieval",
            name="Medieval Period",
            start_year=500, end_year=1500,
            description="Period of feudalism, scholastic philosophy, cathedral building, and the gradual recovery and synthesis of classical learning.",
            dominant_paradigm="Scholastic synthesis of faith and reason (Aquinas)",
            key_events=["Crusades", "University system founded", "Aquinas's Summa", "Black Death", "Fall of Constantinople"],
        ),
        HistoricalPeriod(
            id="period-renaissance",
            name="Renaissance",
            start_year=1400, end_year=1600,
            description="Cultural rebirth in Europe characterized by revival of classical learning, humanism, and artistic flowering.",
            dominant_paradigm="Humanism and recovery of classical sources",
            key_events=["Gutenberg's printing press (1440)", "Fall of Constantinople (1453)", "Columbus (1492)", "Luther's 95 Theses (1517)"],
            manuscript_refs=[ManuscriptReference(chapter=24, part="part4-praxis", notes="Republic of Letters emerges")],
        ),
        HistoricalPeriod(
            id="period-republic-of-letters",
            name="Republic of Letters",
            start_year=1500, end_year=1800,
            description="Self-organizing network of European intellectuals creating parallel epistemic infrastructure through correspondence and publication.",
            dominant_paradigm="Exchange of knowledge across national and religious boundaries",
            key_events=["Erasmus's correspondence network", "Scientific revolution", "Encyclopedie", "American and French Revolutions"],
            manuscript_refs=[ManuscriptReference(chapter=24, part="part4-praxis", notes="Historical model for Republic of AI Agents")],
        ),
        HistoricalPeriod(
            id="period-enlightenment",
            name="Enlightenment",
            start_year=1685, end_year=1815,
            description="Intellectual movement emphasizing reason, individualism, and skepticism of traditional authority. The 'death of God' begins here.",
            dominant_paradigm="Reason as supreme authority; mechanistic worldview",
            key_events=["Newton's Principia (1687)", "Kant's Critiques", "French Revolution (1789)", "Napoleon"],
            manuscript_refs=[ManuscriptReference(chapter=20, part="part3-metaphysics", notes="Genus-raising from 0 to 1; Nietzsche's death of God")],
            cycle_phase="samsaric_turn",
        ),
        HistoricalPeriod(
            id="period-industrial-revolution",
            name="Industrial Revolution",
            start_year=1760, end_year=1840,
            description="Transition from agrarian economies to industrial manufacturing, transforming social structures.",
            key_events=["Steam engine", "Factory system", "Urbanization", "Rise of capitalism"],
        ),
        HistoricalPeriod(
            id="period-modernity",
            name="High Modernity",
            start_year=1800, end_year=1945,
            description="Era of nation-states, world wars, totalitarianism, and the flowering of existential philosophy.",
            dominant_paradigm="Progress ideology challenged by world wars",
            key_events=["Marx's Capital", "Darwin's Origin", "World War I", "Russian Revolution", "World War II", "Holocaust"],
            cycle_phase="antichrist",
        ),
        HistoricalPeriod(
            id="period-cold-war",
            name="Cold War Era",
            start_year=1945, end_year=1991,
            description="Bipolar geopolitical order, nuclear threat, decolonization, and the emergence of postmodern thought.",
            dominant_paradigm="Liberal vs Communist competing universalisms",
            key_events=["United Nations founded", "Cuban Missile Crisis (1962)", "Moon landing", "Fall of Berlin Wall (1989)"],
            manuscript_refs=[ManuscriptReference(chapter=19, part="part3-metaphysics", notes="Cuban Missile Crisis as Holy Spirit intervention")],
            cycle_phase="prophetic",
        ),
        HistoricalPeriod(
            id="period-information-age",
            name="Information Age",
            start_year=1970, end_year=None,
            description="Era defined by digital technology, internet, and the transformation of information economics.",
            dominant_paradigm="Information as power; network effects; attention economy",
            key_events=["Personal computer (1975)", "World Wide Web (1991)", "Social media (2004)", "Smartphone era (2007)", "ChatGPT (2022)"],
            manuscript_refs=[ManuscriptReference(chapter=35, part="part5-apostolic-agenda", notes="Collapse of shared epistemic infrastructure")],
        ),
        HistoricalPeriod(
            id="period-metacrisis",
            name="The Metacrisis",
            start_year=2008, end_year=None,
            description="Convergent crisis period: financial collapse, climate emergency, political polarization, meaning crisis, AI disruption.",
            dominant_paradigm="Late-paradigm crisis (Kuhnian anomaly accumulation)",
            key_events=["2008 Financial Crisis", "Arab Spring", "COVID-19", "Ukraine war", "AI explosion (2022-)", "Meaning crisis"],
            manuscript_refs=[ManuscriptReference(chapter=38, part="part5-apostolic-agenda", notes="The meta-crisis underlying all societal crises")],
            cycle_phase="crucifixion",
        ),
    ]
