"""Intellectual and spiritual traditions."""

from graph.knowledge_entities import Tradition, ManuscriptReference


def create_traditions() -> list[Tradition]:
    return [
        # ===== Ancient Philosophy =====
        Tradition(id="tradition-greek-philosophy", name="Greek Philosophy",
                  description="Philosophical tradition originating in ancient Greece, foundational to Western thought.",
                  time_period="600 BCE - 600 CE", geographic_origin="Greece"),
        Tradition(id="tradition-platonism", name="Platonism",
                  description="Philosophical system of Plato emphasizing the theory of Forms and the pursuit of truth through dialectic.",
                  time_period="400 BCE - present", geographic_origin="Athens",
                  parent_tradition_ids=["tradition-greek-philosophy"]),
        Tradition(id="tradition-aristotelianism", name="Aristotelianism",
                  description="Philosophical tradition of Aristotle emphasizing empiricism, logic, and the four causes.",
                  time_period="350 BCE - present", geographic_origin="Athens",
                  parent_tradition_ids=["tradition-greek-philosophy"]),
        Tradition(id="tradition-stoicism", name="Stoicism",
                  description="Hellenistic school teaching virtue, reason, and living in accordance with nature.",
                  time_period="300 BCE - 200 CE", geographic_origin="Athens",
                  parent_tradition_ids=["tradition-greek-philosophy"]),
        Tradition(id="tradition-neoplatonism", name="Neoplatonism",
                  description="Late antique revival and development of Platonic philosophy, emphasizing emanation from the One.",
                  time_period="200 - 600 CE", geographic_origin="Alexandria",
                  parent_tradition_ids=["tradition-platonism"]),

        # ===== Western Philosophy (Modern) =====
        Tradition(id="tradition-rationalism", name="Continental Rationalism",
                  description="Philosophical movement emphasizing reason as the chief source of knowledge.",
                  time_period="1600-1800", geographic_origin="Europe"),
        Tradition(id="tradition-empiricism", name="British Empiricism",
                  description="Philosophical movement emphasizing sensory experience as the source of knowledge.",
                  time_period="1600-1800", geographic_origin="Britain"),
        Tradition(id="tradition-german-idealism", name="German Idealism",
                  description="Philosophical movement from Kant through Hegel emphasizing the constitutive role of mind in experience.",
                  time_period="1781-1831", geographic_origin="Germany"),
        Tradition(id="tradition-existentialism", name="Existentialism",
                  description="Philosophical movement emphasizing individual freedom, choice, and the absurdity of existence.",
                  time_period="1840-present", geographic_origin="Europe"),
        Tradition(id="tradition-phenomenology-school", name="Phenomenological Movement",
                  description="Philosophical tradition founded by Husserl studying structures of consciousness and experience.",
                  time_period="1900-present", geographic_origin="Germany"),
        Tradition(id="tradition-vienna-circle", name="Vienna Circle / Logical Positivism",
                  description="Philosophical movement advocating scientific empiricism and logical analysis of language.",
                  time_period="1924-1936", geographic_origin="Vienna"),
        Tradition(id="tradition-critical-theory", name="Critical Theory",
                  description="Social philosophy derived from Marxism examining domination, liberation, and cultural critique.",
                  time_period="1930-present", geographic_origin="Frankfurt"),
        Tradition(id="tradition-poststructuralism", name="Poststructuralism",
                  description="Movement questioning fixed meaning, emphasizing power, discourse, and deconstruction.",
                  time_period="1960-present", geographic_origin="France"),
        Tradition(id="tradition-pragmatism", name="Pragmatism",
                  description="American philosophical tradition evaluating ideas by their practical consequences.",
                  time_period="1870-present", geographic_origin="United States"),
        Tradition(id="tradition-process-philosophy", name="Process Philosophy",
                  description="Tradition emphasizing becoming over being, process over substance.",
                  time_period="1929-present", geographic_origin="England/United States"),

        # ===== Christianity =====
        Tradition(id="tradition-christianity", name="Christianity",
                  description="Abrahamic monotheistic religion based on the life and teachings of Jesus Christ.",
                  time_period="30 CE - present", geographic_origin="Judea/Palestine"),
        Tradition(id="tradition-orthodox-christianity", name="Eastern Orthodox Christianity",
                  description="Eastern Christian tradition emphasizing theosis, liturgy, and the patristic inheritance.",
                  time_period="325 CE - present", geographic_origin="Byzantine Empire",
                  parent_tradition_ids=["tradition-christianity"]),
        Tradition(id="tradition-catholic-christianity", name="Roman Catholicism",
                  description="Western Christian tradition centered on papal authority and scholastic theology.",
                  time_period="325 CE - present", geographic_origin="Rome",
                  parent_tradition_ids=["tradition-christianity"]),
        Tradition(id="tradition-protestant-christianity", name="Protestantism",
                  description="Western Christian movement originating in the Reformation, emphasizing scripture and faith.",
                  time_period="1517 - present", geographic_origin="Germany",
                  parent_tradition_ids=["tradition-christianity"]),
        Tradition(id="tradition-syriac-christianity", name="Syriac Christianity",
                  description="Eastern Christian tradition using Syriac liturgical language, bridge between Christianity and Islam.",
                  time_period="100 CE - present", geographic_origin="Syria/Mesopotamia",
                  parent_tradition_ids=["tradition-christianity"],
                  manuscript_refs=[ManuscriptReference(chapter=17, part="part3-metaphysics", notes="Key bridge tradition for Quran-Christian reconciliation")]),
        Tradition(id="tradition-maronite", name="Maronite Christianity",
                  description="Eastern Catholic church rooted in Syriac tradition, centered in Lebanon.",
                  time_period="400 CE - present", geographic_origin="Lebanon",
                  parent_tradition_ids=["tradition-syriac-christianity"],
                  manuscript_refs=[ManuscriptReference(chapter=22, part="part3-metaphysics", notes="Grace's tradition; embodied theology")]),

        # ===== Judaism =====
        Tradition(id="tradition-judaism", name="Judaism",
                  description="Abrahamic monotheistic religion of the Jewish people, based on Torah and oral law.",
                  time_period="1200 BCE - present", geographic_origin="Ancient Israel"),
        Tradition(id="tradition-rabbinic-judaism", name="Rabbinic Judaism",
                  description="Post-Temple Judaism based on Talmudic interpretation and rabbinic authority.",
                  time_period="200 CE - present", geographic_origin="Palestine/Babylon",
                  parent_tradition_ids=["tradition-judaism"]),

        # ===== Islam =====
        Tradition(id="tradition-islam", name="Islam",
                  description="Abrahamic monotheistic religion founded by Prophet Muhammad, based on the Quran.",
                  time_period="610 CE - present", geographic_origin="Mecca"),
        Tradition(id="tradition-sunni-islam", name="Sunni Islam",
                  description="Largest branch of Islam, following the Sunnah and consensus of the community.",
                  time_period="632 CE - present", geographic_origin="Arabia",
                  parent_tradition_ids=["tradition-islam"]),
        Tradition(id="tradition-shia-islam", name="Shia Islam",
                  description="Branch of Islam following the Ahl al-Bayt (family of the Prophet).",
                  time_period="632 CE - present", geographic_origin="Arabia",
                  parent_tradition_ids=["tradition-islam"]),
        Tradition(id="tradition-sufism", name="Sufism",
                  description="Islamic mystical tradition emphasizing inner, esoteric dimensions of faith.",
                  time_period="800 CE - present", geographic_origin="Persia/Arabia",
                  parent_tradition_ids=["tradition-islam"],
                  manuscript_refs=[ManuscriptReference(chapter=17, part="part3-metaphysics"), ManuscriptReference(chapter=18, part="part3-metaphysics")]),

        # ===== Hinduism =====
        Tradition(id="tradition-hinduism", name="Hinduism",
                  description="Ancient Indian religious and philosophical tradition based on Vedas, Upanishads, and diverse schools.",
                  time_period="1500 BCE - present", geographic_origin="Indian subcontinent"),
        Tradition(id="tradition-advaita-vedanta", name="Advaita Vedanta",
                  description="Non-dualistic Hindu school teaching the identity of Atman (self) and Brahman (ultimate reality).",
                  time_period="800 CE - present", geographic_origin="India",
                  parent_tradition_ids=["tradition-hinduism"],
                  manuscript_refs=[ManuscriptReference(chapter=20, part="part3-metaphysics", notes="Omnipresence correction")]),
        Tradition(id="tradition-yoga", name="Yoga Tradition",
                  description="Indian tradition of mental, physical, and spiritual practices aimed at controlling mind and body.",
                  time_period="500 BCE - present", geographic_origin="India",
                  parent_tradition_ids=["tradition-hinduism"]),
        Tradition(id="tradition-tantra", name="Tantra",
                  description="Esoteric traditions in Hinduism and Buddhism emphasizing embodied practice and ritual.",
                  time_period="500 CE - present", geographic_origin="India",
                  parent_tradition_ids=["tradition-hinduism"]),

        # ===== Buddhism =====
        Tradition(id="tradition-buddhism", name="Buddhism",
                  description="Religious and philosophical tradition founded by Siddhartha Gautama (the Buddha).",
                  time_period="500 BCE - present", geographic_origin="India"),
        Tradition(id="tradition-theravada", name="Theravada Buddhism",
                  description="Oldest surviving Buddhist school emphasizing the Pali Canon and individual liberation.",
                  time_period="300 BCE - present", geographic_origin="India/Sri Lanka",
                  parent_tradition_ids=["tradition-buddhism"]),
        Tradition(id="tradition-mahayana", name="Mahayana Buddhism",
                  description="Buddhist tradition emphasizing the bodhisattva path and universal liberation.",
                  time_period="100 BCE - present", geographic_origin="India",
                  parent_tradition_ids=["tradition-buddhism"]),
        Tradition(id="tradition-zen", name="Zen Buddhism",
                  description="East Asian Buddhist school emphasizing meditation, koans, and direct insight.",
                  time_period="500 CE - present", geographic_origin="China/Japan",
                  parent_tradition_ids=["tradition-mahayana"]),
        Tradition(id="tradition-tibetan-buddhism", name="Tibetan Buddhism",
                  description="Form of Buddhism practiced in Tibet combining Mahayana philosophy with Vajrayana practices.",
                  time_period="700 CE - present", geographic_origin="Tibet",
                  parent_tradition_ids=["tradition-mahayana"]),

        # ===== Chinese Philosophy =====
        Tradition(id="tradition-taoism", name="Taoism",
                  description="Chinese philosophical and religious tradition emphasizing the Tao (Way), wu wei, and harmony with nature.",
                  time_period="400 BCE - present", geographic_origin="China",
                  manuscript_refs=[ManuscriptReference(chapter=18, part="part3-metaphysics")]),
        Tradition(id="tradition-confucianism", name="Confucianism",
                  description="Chinese ethical and philosophical system emphasizing social harmony, filial piety, and ritual propriety.",
                  time_period="500 BCE - present", geographic_origin="China"),

        # ===== African Philosophy =====
        Tradition(id="tradition-african-philosophy", name="African Philosophy",
                  description="Diverse philosophical traditions from Africa including Ubuntu, Bantu ontology, and oral wisdom.",
                  time_period="ancient - present", geographic_origin="Africa",
                  manuscript_refs=[ManuscriptReference(chapter=18, part="part3-metaphysics")]),
        Tradition(id="tradition-ubuntu", name="Ubuntu",
                  description="Southern African philosophy of radical relationality: 'I am because we are.'",
                  time_period="ancient - present", geographic_origin="Southern Africa",
                  parent_tradition_ids=["tradition-african-philosophy"]),

        # ===== Indigenous Traditions =====
        Tradition(id="tradition-indigenous-american", name="Indigenous American Traditions",
                  description="Diverse philosophical and spiritual traditions of the Americas' indigenous peoples.",
                  time_period="ancient - present", geographic_origin="Americas",
                  manuscript_refs=[ManuscriptReference(chapter=18, part="part3-metaphysics")]),
        Tradition(id="tradition-haudenosaunee", name="Haudenosaunee (Iroquois)",
                  description="Confederacy governance tradition including the Great Law of Peace and clan mother leadership.",
                  time_period="1000 CE - present", geographic_origin="North America",
                  parent_tradition_ids=["tradition-indigenous-american"]),

        # ===== Psychoanalytic Traditions =====
        Tradition(id="tradition-psychoanalysis", name="Psychoanalysis",
                  description="Tradition of psychological theory and therapy originating with Freud.",
                  time_period="1895 - present", geographic_origin="Vienna"),
        Tradition(id="tradition-jungian", name="Jungian Psychology",
                  description="Analytical psychology developed by Carl Jung emphasizing collective unconscious and individuation.",
                  time_period="1913 - present", geographic_origin="Switzerland",
                  parent_tradition_ids=["tradition-psychoanalysis"]),
        Tradition(id="tradition-gestalt", name="Gestalt Therapy",
                  description="Experiential psychotherapy emphasizing present awareness, embodied experience, and the paradoxical theory of change.",
                  time_period="1951 - present", geographic_origin="United States",
                  parent_tradition_ids=["tradition-psychoanalysis"]),
        Tradition(id="tradition-cbt", name="Cognitive-Behavioral Therapy",
                  description="Evidence-based psychotherapy addressing dysfunctional cognitions, emotions, and behaviors.",
                  time_period="1960 - present", geographic_origin="United States"),

        # ===== Contemporary Movements =====
        Tradition(id="tradition-rationalist-community", name="Rationalist Community (LessWrong)",
                  description="Online community focused on Bayesian rationality, AI safety, and overcoming cognitive biases.",
                  time_period="2009 - present", geographic_origin="Online/San Francisco",
                  manuscript_refs=[ManuscriptReference(chapter=12, part="part2-epistemology")]),
        Tradition(id="tradition-ea", name="Effective Altruism",
                  description="Movement applying evidence and reason to determine the most effective ways to benefit others.",
                  time_period="2011 - present", geographic_origin="Oxford/San Francisco",
                  manuscript_refs=[ManuscriptReference(chapter=12, part="part2-epistemology")]),
        Tradition(id="tradition-progress-studies", name="Progress Studies",
                  description="Intellectual movement studying the causes and conditions of human progress.",
                  time_period="2019 - present", geographic_origin="United States",
                  manuscript_refs=[ManuscriptReference(chapter=12, part="part2-epistemology")]),
        Tradition(id="tradition-eacc", name="Effective Accelerationism (e/acc)",
                  description="Movement advocating acceleration of technological progress and complexity emergence.",
                  time_period="2022 - present", geographic_origin="Online/San Francisco",
                  manuscript_refs=[ManuscriptReference(chapter=12, part="part2-epistemology")]),
        Tradition(id="tradition-complexity-science", name="Complexity Science",
                  description="Interdisciplinary study of complex adaptive systems, emergence, and self-organization.",
                  time_period="1984 - present", geographic_origin="Santa Fe, New Mexico"),
        Tradition(id="tradition-behavioral-economics", name="Behavioral Economics",
                  description="Field combining psychology and economics to study human decision-making under bounded rationality.",
                  time_period="1979 - present", geographic_origin="Israel/United States",
                  manuscript_refs=[ManuscriptReference(chapter=12, part="part2-epistemology")]),
    ]
