"""Works — books, papers, scriptures, and other intellectual products from Appendix B."""

from graph.knowledge_entities import Work, WorkType, ManuscriptReference


def create_works() -> list[Work]:
    return [
        # ===== Core Framework Works =====
        Work(id="work-geb", title="Godel, Escher, Bach: An Eternal Golden Braid",
             author_ids=["thinker-hofstadter"], year=1979, work_type=WorkType.BOOK,
             concepts_introduced=["concept-strange-loop"],
             manuscript_refs=[ManuscriptReference(chapter=16, part="part3-metaphysics", notes="Trinity as strange loop")]),
        Work(id="work-structure-scientific-revolutions", title="The Structure of Scientific Revolutions",
             author_ids=["thinker-kuhn"], year=1962, work_type=WorkType.BOOK,
             concepts_introduced=["concept-paradigm-shift", "concept-normal-science", "concept-anomaly-accumulation", "concept-incommensurability"],
             manuscript_refs=[ManuscriptReference(chapter=6, part="part2-epistemology")]),
        Work(id="work-logic-scientific-discovery", title="The Logic of Scientific Discovery",
             author_ids=["thinker-popper"], year=1934, work_type=WorkType.BOOK,
             concepts_introduced=["concept-falsifiability", "concept-demarcation-problem"],
             manuscript_refs=[ManuscriptReference(chapter=5, part="part2-epistemology")]),
        Work(id="work-open-society", title="The Open Society and Its Enemies",
             author_ids=["thinker-popper"], year=1945, work_type=WorkType.BOOK,
             concepts_introduced=["concept-open-society"],
             manuscript_refs=[ManuscriptReference(chapter=5, part="part2-epistemology")]),
        Work(id="work-causality", title="Causality: Models, Reasoning, and Inference",
             author_ids=["thinker-pearl"], year=2000, work_type=WorkType.BOOK,
             concepts_introduced=["concept-do-calculus", "concept-causal-hierarchy", "concept-backdoor-criterion"],
             manuscript_refs=[ManuscriptReference(chapter=10, part="part2-epistemology")]),
        Work(id="work-book-of-why", title="The Book of Why",
             author_ids=["thinker-pearl"], year=2018, work_type=WorkType.BOOK,
             concepts_developed=["concept-causal-hierarchy", "concept-simpsons-paradox"],
             manuscript_refs=[ManuscriptReference(chapter=10, part="part2-epistemology")]),
        Work(id="work-destruction-creation", title="Destruction and Creation",
             author_ids=["thinker-boyd"], year=1976, work_type=WorkType.PAPER,
             concepts_introduced=["concept-dialectical-engine", "concept-destructive-deduction", "concept-creative-induction"],
             manuscript_refs=[ManuscriptReference(chapter=11, part="part2-epistemology", notes="Compressed version of the entire theological-epistemological framework")]),
        Work(id="work-zamm", title="Zen and the Art of Motorcycle Maintenance",
             author_ids=["thinker-pirsig"], year=1974, work_type=WorkType.BOOK,
             concepts_introduced=["concept-quality"],
             manuscript_refs=[ManuscriptReference(chapter=26, part="part4-praxis")]),

        # ===== Taleb's Incerto =====
        Work(id="work-black-swan", title="The Black Swan",
             author_ids=["thinker-taleb"], year=2007, work_type=WorkType.BOOK,
             concepts_introduced=["concept-black-swan"],
             manuscript_refs=[ManuscriptReference(chapter=7, part="part2-epistemology")]),
        Work(id="work-antifragile", title="Antifragile: Things That Gain from Disorder",
             author_ids=["thinker-taleb"], year=2012, work_type=WorkType.BOOK,
             concepts_introduced=["concept-antifragility", "concept-lindy-effect"]),
        Work(id="work-skin-in-game", title="Skin in the Game",
             author_ids=["thinker-taleb"], year=2018, work_type=WorkType.BOOK,
             concepts_introduced=["concept-skin-in-the-game"]),
        Work(id="work-fooled-by-randomness", title="Fooled by Randomness",
             author_ids=["thinker-taleb"], year=2001, work_type=WorkType.BOOK),

        # ===== Existentialist Works =====
        Work(id="work-being-nothingness", title="Being and Nothingness",
             author_ids=["thinker-sartre"], year=1943, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-existentialism"],
             concepts_introduced=["concept-mauvaise-foi"],
             manuscript_refs=[ManuscriptReference(chapter=20, part="part3-metaphysics", notes="Genus-1 philosophy")]),
        Work(id="work-myth-sisyphus", title="The Myth of Sisyphus",
             author_ids=["thinker-camus"], year=1942, work_type=WorkType.ESSAY,
             tradition_ids=["tradition-existentialism"],
             concepts_introduced=["concept-absurd"],
             manuscript_refs=[ManuscriptReference(chapter=20, part="part3-metaphysics")]),
        Work(id="work-plague", title="The Plague",
             author_ids=["thinker-camus"], year=1947, work_type=WorkType.BOOK,
             tradition_ids=["tradition-existentialism"],
             manuscript_refs=[ManuscriptReference(chapter=20, part="part3-metaphysics", notes="Torus ethic: fight suffering because it's there")]),
        Work(id="work-rebel", title="The Rebel",
             author_ids=["thinker-camus"], year=1951, work_type=WorkType.BOOK,
             tradition_ids=["tradition-existentialism"]),
        Work(id="work-stranger", title="The Stranger",
             author_ids=["thinker-camus"], year=1942, work_type=WorkType.BOOK,
             tradition_ids=["tradition-existentialism"]),
        Work(id="work-second-sex", title="The Second Sex",
             author_ids=["thinker-de-beauvoir"], year=1949, work_type=WorkType.BOOK,
             tradition_ids=["tradition-existentialism"],
             concepts_introduced=["concept-situated-freedom"]),
        Work(id="work-ethics-ambiguity", title="The Ethics of Ambiguity",
             author_ids=["thinker-de-beauvoir"], year=1947, work_type=WorkType.BOOK,
             tradition_ids=["tradition-existentialism"]),
        Work(id="work-being-time", title="Being and Time",
             author_ids=["thinker-heidegger"], year=1927, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-phenomenology-school"],
             concepts_introduced=["concept-das-man", "concept-being-toward-death"],
             manuscript_refs=[ManuscriptReference(chapter=20, part="part3-metaphysics")]),
        Work(id="work-nausea", title="Nausea",
             author_ids=["thinker-sartre"], year=1938, work_type=WorkType.BOOK,
             tradition_ids=["tradition-existentialism"]),

        # ===== Nietzsche =====
        Work(id="work-zarathustra", title="Thus Spoke Zarathustra",
             author_ids=["thinker-nietzsche"], year=1883, work_type=WorkType.BOOK,
             concepts_introduced=["concept-ubermensch", "concept-eternal-recurrence"],
             manuscript_refs=[ManuscriptReference(chapter=20, part="part3-metaphysics")]),
        Work(id="work-beyond-good-evil", title="Beyond Good and Evil",
             author_ids=["thinker-nietzsche"], year=1886, work_type=WorkType.BOOK,
             concepts_introduced=["concept-will-to-power"]),
        Work(id="work-genealogy-morals", title="On the Genealogy of Morals",
             author_ids=["thinker-nietzsche"], year=1887, work_type=WorkType.BOOK),
        Work(id="work-gay-science", title="The Gay Science",
             author_ids=["thinker-nietzsche"], year=1882, work_type=WorkType.BOOK,
             concepts_introduced=["concept-death-of-god"]),

        # ===== Dostoevsky =====
        Work(id="work-brothers-karamazov", title="The Brothers Karamazov",
             author_ids=["thinker-dostoevsky"], year=1880, work_type=WorkType.BOOK,
             concepts_introduced=["concept-grand-inquisitor"],
             manuscript_refs=[ManuscriptReference(chapter=21, part="part3-metaphysics", notes="Ivan/Dmitri/Alyosha as intellect/body/prophet")]),
        Work(id="work-notes-underground", title="Notes from Underground",
             author_ids=["thinker-dostoevsky"], year=1864, work_type=WorkType.BOOK),
        Work(id="work-idiot", title="The Idiot",
             author_ids=["thinker-dostoevsky"], year=1869, work_type=WorkType.BOOK),
        Work(id="work-demons", title="Demons",
             author_ids=["thinker-dostoevsky"], year=1872, work_type=WorkType.BOOK),

        # ===== Political Philosophy =====
        Work(id="work-eichmann-jerusalem", title="Eichmann in Jerusalem: A Report on the Banality of Evil",
             author_ids=["thinker-arendt"], year=1963, work_type=WorkType.BOOK,
             concepts_introduced=["concept-banality-of-evil"],
             manuscript_refs=[ManuscriptReference(chapter=2, part="part1-psychology")]),
        Work(id="work-human-condition", title="The Human Condition",
             author_ids=["thinker-arendt"], year=1958, work_type=WorkType.BOOK,
             concepts_introduced=["concept-natality"]),
        Work(id="work-origins-totalitarianism", title="The Origins of Totalitarianism",
             author_ids=["thinker-arendt"], year=1951, work_type=WorkType.BOOK),
        Work(id="work-gravity-grace", title="Gravity and Grace",
             author_ids=["thinker-weil"], year=1947, work_type=WorkType.BOOK,
             concepts_introduced=["concept-gravity-and-grace", "concept-malheur", "concept-attention-as-prayer"]),
        Work(id="work-waiting-god", title="Waiting for God",
             author_ids=["thinker-weil"], year=1951, work_type=WorkType.BOOK),
        Work(id="work-need-roots", title="The Need for Roots",
             author_ids=["thinker-weil"], year=1949, work_type=WorkType.BOOK),

        # ===== Foucault =====
        Work(id="work-discipline-punish", title="Discipline and Punish",
             author_ids=["thinker-foucault"], year=1975, work_type=WorkType.BOOK,
             tradition_ids=["tradition-poststructuralism"],
             concepts_introduced=["concept-biopower"]),
        Work(id="work-order-things", title="The Order of Things",
             author_ids=["thinker-foucault"], year=1966, work_type=WorkType.BOOK,
             tradition_ids=["tradition-poststructuralism"],
             concepts_introduced=["concept-power-knowledge"]),

        # ===== Tier 2 Works =====
        Work(id="work-ecology-mind", title="Steps to an Ecology of Mind",
             author_ids=["thinker-bateson"], year=1972, work_type=WorkType.BOOK),
        Work(id="work-violence-sacred", title="Violence and the Sacred",
             author_ids=["thinker-girard"], year=1972, work_type=WorkType.BOOK,
             concepts_introduced=["concept-mimetic-desire", "concept-scapegoat-mechanism"]),
        Work(id="work-things-hidden", title="Things Hidden Since the Foundation of the World",
             author_ids=["thinker-girard"], year=1978, work_type=WorkType.BOOK),
        Work(id="work-deschooling", title="Deschooling Society",
             author_ids=["thinker-illich"], year=1971, work_type=WorkType.BOOK),
        Work(id="work-tools-conviviality", title="Tools for Conviviality",
             author_ids=["thinker-illich"], year=1973, work_type=WorkType.BOOK),
        Work(id="work-understanding-media", title="Understanding Media",
             author_ids=["thinker-mcluhan"], year=1964, work_type=WorkType.BOOK),
        Work(id="work-burnout-society", title="The Burnout Society",
             author_ids=["thinker-han"], year=2010, work_type=WorkType.BOOK),
        Work(id="work-seeing-like-state", title="Seeing Like a State",
             author_ids=["thinker-scott"], year=1998, work_type=WorkType.BOOK),
        Work(id="work-cyborg-manifesto", title="A Cyborg Manifesto",
             author_ids=["thinker-haraway"], year=1985, work_type=WorkType.ESSAY),
        Work(id="work-wretched-earth", title="The Wretched of the Earth",
             author_ids=["thinker-fanon"], year=1961, work_type=WorkType.BOOK),
        Work(id="work-totality-infinity", title="Totality and Infinity",
             author_ids=["thinker-levinas"], year=1961, work_type=WorkType.TREATISE,
             concepts_introduced=["concept-face-of-the-other"]),
        Work(id="work-reasons-persons", title="Reasons and Persons",
             author_ids=["thinker-parfit"], year=1984, work_type=WorkType.BOOK,
             concepts_introduced=["concept-personal-identity-as-degree", "concept-repugnant-conclusion"]),
        Work(id="work-on-what-matters", title="On What Matters",
             author_ids=["thinker-parfit"], year=2011, work_type=WorkType.BOOK),
        Work(id="work-expanding-circle", title="The Expanding Circle",
             author_ids=["thinker-singer"], year=1981, work_type=WorkType.BOOK,
             concepts_introduced=["concept-expanding-circle"]),
        Work(id="work-animal-liberation", title="Animal Liberation",
             author_ids=["thinker-singer"], year=1975, work_type=WorkType.BOOK),
        Work(id="work-gulag-archipelago", title="The Gulag Archipelago",
             author_ids=["thinker-solzhenitsyn"], year=1973, work_type=WorkType.BOOK),

        # ===== Tier 3 =====
        Work(id="work-spinoza-ethics", title="Ethics",
             author_ids=["thinker-spinoza"], year=1677, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-rationalism"],
             concepts_introduced=["concept-deus-sive-natura"],
             manuscript_refs=[ManuscriptReference(chapter=16, part="part3-metaphysics", notes="Bottom-up path: Hobbes → Spinoza → emergence")]),
        Work(id="work-tractatus", title="Tractatus Logico-Philosophicus",
             author_ids=["thinker-wittgenstein"], year=1921, work_type=WorkType.TREATISE),
        Work(id="work-philosophical-investigations", title="Philosophical Investigations",
             author_ids=["thinker-wittgenstein"], year=1953, work_type=WorkType.BOOK,
             concepts_introduced=["concept-language-games"]),

        # ===== Psychoanalysis =====
        Work(id="work-interpretation-dreams", title="The Interpretation of Dreams",
             author_ids=["thinker-freud"], year=1899, work_type=WorkType.BOOK,
             tradition_ids=["tradition-psychoanalysis"]),
        Work(id="work-beyond-pleasure", title="Beyond the Pleasure Principle",
             author_ids=["thinker-freud"], year=1920, work_type=WorkType.BOOK,
             tradition_ids=["tradition-psychoanalysis"],
             concepts_introduced=["concept-repetition-compulsion"]),
        Work(id="work-man-symbols", title="Man and His Symbols",
             author_ids=["thinker-jung"], year=1964, work_type=WorkType.BOOK,
             tradition_ids=["tradition-jungian"],
             concepts_introduced=["concept-collective-unconscious"]),
        Work(id="work-aion", title="Aion: Researches into the Phenomenology of the Self",
             author_ids=["thinker-jung"], year=1951, work_type=WorkType.BOOK,
             tradition_ids=["tradition-jungian"]),
        Work(id="work-answer-job", title="Answer to Job",
             author_ids=["thinker-jung"], year=1952, work_type=WorkType.BOOK,
             tradition_ids=["tradition-jungian"]),
        Work(id="work-red-book", title="The Red Book (Liber Novus)",
             author_ids=["thinker-jung"], year=2009, work_type=WorkType.BOOK,
             tradition_ids=["tradition-jungian"]),
        Work(id="work-understanding-human-nature", title="Understanding Human Nature",
             author_ids=["thinker-adler"], year=1927, work_type=WorkType.BOOK,
             concepts_introduced=["concept-inferiority-complex"]),
        Work(id="work-gestalt-therapy", title="Gestalt Therapy: Excitement and Growth in the Human Personality",
             author_ids=["thinker-perls"], year=1951, work_type=WorkType.BOOK,
             tradition_ids=["tradition-gestalt"],
             concepts_introduced=["concept-paradoxical-theory-of-change"]),
        Work(id="work-cognitive-therapy", title="Cognitive Therapy and the Emotional Disorders",
             author_ids=["thinker-beck"], year=1976, work_type=WorkType.BOOK,
             tradition_ids=["tradition-cbt"],
             concepts_introduced=["concept-cognitive-restructuring"]),
        Work(id="work-dbt-skills", title="DBT Skills Training Manual",
             author_ids=["thinker-linehan"], year=1993, work_type=WorkType.BOOK),
        Work(id="work-ifs-therapy", title="Internal Family Systems Therapy",
             author_ids=["thinker-schwartz"], year=1995, work_type=WorkType.BOOK,
             concepts_introduced=["concept-internal-family-systems"]),
        Work(id="work-act-get-out", title="Get Out of Your Mind and Into Your Life",
             author_ids=["thinker-hayes"], year=2005, work_type=WorkType.BOOK,
             concepts_introduced=["concept-defusion"]),
        Work(id="work-thinking-fast-slow", title="Thinking, Fast and Slow",
             author_ids=["thinker-kahneman"], year=2011, work_type=WorkType.BOOK,
             concepts_introduced=["concept-system1-system2", "concept-cognitive-biases"]),

        # ===== Theology & Patristics =====
        Work(id="work-confessions", title="Confessions",
             author_ids=["thinker-augustine"], year=397, work_type=WorkType.BOOK,
             tradition_ids=["tradition-catholic-christianity"]),
        Work(id="work-city-of-god", title="The City of God",
             author_ids=["thinker-augustine"], year=426, work_type=WorkType.BOOK,
             tradition_ids=["tradition-catholic-christianity"]),
        Work(id="work-summa-theologica", title="Summa Theologica",
             author_ids=["thinker-aquinas"], year=1274, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-catholic-christianity"]),
        Work(id="work-fusus-al-hikam", title="Fusus al-Hikam (Bezels of Wisdom)",
             author_ids=["thinker-ibn-arabi"], year=1229, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-sufism"],
             concepts_introduced=["concept-wahdat-al-wujud"]),
        Work(id="work-deliverance-error", title="Deliverance from Error (Al-Munqidh min al-Dalal)",
             author_ids=["thinker-al-ghazali"], year=1100, work_type=WorkType.BOOK,
             tradition_ids=["tradition-sufism"]),
        Work(id="work-masnavi", title="Masnavi-i Ma'navi",
             author_ids=["thinker-rumi"], year=1273, work_type=WorkType.POEM,
             tradition_ids=["tradition-sufism"]),
        Work(id="work-muqaddimah", title="Muqaddimah (Prolegomena)",
             author_ids=["thinker-ibn-khaldun"], year=1377, work_type=WorkType.BOOK,
             concepts_introduced=["concept-asabiyyah"]),

        # ===== Eastern Philosophy =====
        Work(id="work-mulamadhyamakakarika", title="Mulamadhyamakakarika (Fundamental Verses on the Middle Way)",
             author_ids=["thinker-nagarjuna"], year=200, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-mahayana"],
             concepts_introduced=["concept-sunyata"]),
        Work(id="work-tao-te-ching", title="Tao Te Ching",
             author_ids=["thinker-lao-tzu"], year=-400, work_type=WorkType.SCRIPTURE,
             tradition_ids=["tradition-taoism"],
             concepts_introduced=["concept-tao", "concept-wu-wei"]),
        Work(id="work-yoga-sutras", title="Yoga Sutras",
             author_ids=["thinker-patanjali"], year=-200, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-yoga"]),
        Work(id="work-shobogenzo", title="Shobogenzo",
             author_ids=["thinker-dogen"], year=1240, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-zen"]),
        Work(id="work-heart-buddha-teaching", title="The Heart of the Buddha's Teaching",
             author_ids=["thinker-thich-nhat-hanh"], year=1998, work_type=WorkType.BOOK,
             tradition_ids=["tradition-mahayana"]),
        Work(id="work-bhagavad-gita", title="Bhagavad Gita",
             year=-200, work_type=WorkType.SCRIPTURE,
             tradition_ids=["tradition-hinduism"],
             concepts_introduced=["concept-nishkama-karma"]),
        Work(id="work-upanishads", title="Upanishads",
             year=-800, work_type=WorkType.SCRIPTURE,
             tradition_ids=["tradition-hinduism"],
             concepts_introduced=["concept-brahman-atman-identity"]),

        # ===== Scriptures =====
        Work(id="work-hebrew-bible", title="Hebrew Bible (Tanakh)",
             year=-500, work_type=WorkType.SCRIPTURE,
             tradition_ids=["tradition-judaism"],
             manuscript_refs=[ManuscriptReference(chapter=13, part="part3-metaphysics")]),
        Work(id="work-new-testament", title="New Testament",
             year=100, work_type=WorkType.SCRIPTURE,
             tradition_ids=["tradition-christianity"],
             manuscript_refs=[ManuscriptReference(chapter=15, part="part3-metaphysics")]),
        Work(id="work-quran", title="The Quran",
             year=632, work_type=WorkType.SCRIPTURE,
             tradition_ids=["tradition-islam"],
             manuscript_refs=[ManuscriptReference(chapter=17, part="part3-metaphysics")]),

        # ===== Ancient Philosophy =====
        Work(id="work-republic", title="The Republic",
             author_ids=["thinker-plato"], year=-375, work_type=WorkType.DIALOGUE,
             tradition_ids=["tradition-platonism"],
             manuscript_refs=[ManuscriptReference(chapter=25, part="part4-praxis", notes="Philosopher-kings model for Republic of AI Agents")]),
        Work(id="work-symposium", title="Symposium",
             author_ids=["thinker-plato"], year=-385, work_type=WorkType.DIALOGUE,
             tradition_ids=["tradition-platonism"]),
        Work(id="work-nicomachean-ethics", title="Nicomachean Ethics",
             author_ids=["thinker-aristotle"], year=-340, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-aristotelianism"]),
        Work(id="work-physics-aristotle", title="Physics",
             author_ids=["thinker-aristotle"], year=-350, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-aristotelianism"]),
        Work(id="work-metaphysics-aristotle", title="Metaphysics",
             author_ids=["thinker-aristotle"], year=-350, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-aristotelianism"]),
        Work(id="work-enneads", title="Enneads",
             author_ids=["thinker-plotinus"], year=270, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-neoplatonism"]),

        # ===== Literature =====
        Work(id="work-paradise-lost", title="Paradise Lost",
             author_ids=["thinker-milton"], year=1667, work_type=WorkType.POEM,
             manuscript_refs=[ManuscriptReference(chapter=14, part="part3-metaphysics", notes="Satan as engine of dialectic; the Fall framework")]),
        Work(id="work-dune", title="Dune",
             author_ids=["thinker-herbert"], year=1965, work_type=WorkType.BOOK,
             manuscript_refs=[ManuscriptReference(chapter=27, part="part4-praxis", notes="Warning about unforkable power structures")]),
        Work(id="work-jesus-son-man", title="Jesus the Son of Man",
             author_ids=["thinker-gibran"], year=1928, work_type=WorkType.BOOK),
        Work(id="work-dorian-gray", title="The Picture of Dorian Gray",
             author_ids=["thinker-wilde"], year=1890, work_type=WorkType.BOOK,
             manuscript_refs=[ManuscriptReference(chapter=23, part="part3-metaphysics", notes="Aestheticism as own end = danger")]),
        Work(id="work-world-will-representation", title="The World as Will and Representation",
             author_ids=["thinker-schopenhauer"], year=1818, work_type=WorkType.TREATISE,
             manuscript_refs=[ManuscriptReference(chapter=23, part="part3-metaphysics")]),

        # ===== Hegel =====
        Work(id="work-phenomenology-spirit", title="Phenomenology of Spirit",
             author_ids=["thinker-hegel"], year=1807, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-german-idealism"],
             manuscript_refs=[ManuscriptReference(chapter=11, part="part2-epistemology")]),
        Work(id="work-science-logic", title="Science of Logic",
             author_ids=["thinker-hegel"], year=1816, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-german-idealism"]),

        # ===== Modern Thinkers =====
        Work(id="work-hero-thousand-faces", title="The Hero with a Thousand Faces",
             author_ids=["thinker-campbell"], year=1949, work_type=WorkType.BOOK,
             concepts_introduced=["concept-monomyth", "concept-heros-return"],
             manuscript_refs=[ManuscriptReference(chapter=26, part="part4-praxis")]),
        Work(id="work-role-individual", title="On the Role of the Individual in History",
             author_ids=["thinker-plekhanov"], year=1898, work_type=WorkType.ESSAY,
             concepts_introduced=["concept-structural-contingency"],
             manuscript_refs=[ManuscriptReference(chapter=26, part="part4-praxis")]),
        Work(id="work-master-emissary", title="The Master and His Emissary",
             author_ids=["thinker-mcgilchrist"], year=2009, work_type=WorkType.BOOK,
             concepts_introduced=["concept-left-right-hemisphere"],
             manuscript_refs=[ManuscriptReference(chapter=1, part="part1-psychology")]),
        Work(id="work-bicameral-mind", title="The Origin of Consciousness in the Breakdown of the Bicameral Mind",
             author_ids=["thinker-jaynes"], year=1976, work_type=WorkType.BOOK,
             concepts_introduced=["concept-bicameral-mind"],
             manuscript_refs=[ManuscriptReference(chapter=13, part="part3-metaphysics")]),
        Work(id="work-phenomenon-man", title="The Phenomenon of Man",
             author_ids=["thinker-teilhard"], year=1955, work_type=WorkType.BOOK,
             tradition_ids=["tradition-process-philosophy"]),
        Work(id="work-process-reality", title="Process and Reality",
             author_ids=["thinker-whitehead"], year=1929, work_type=WorkType.TREATISE,
             tradition_ids=["tradition-process-philosophy"]),

        # ===== Economics =====
        Work(id="work-capital-marx", title="Das Kapital",
             author_ids=["thinker-marx"], year=1867, work_type=WorkType.BOOK),
        Work(id="work-road-serfdom", title="The Road to Serfdom",
             author_ids=["thinker-hayek"], year=1944, work_type=WorkType.BOOK,
             concepts_introduced=["concept-spontaneous-order"]),
        Work(id="work-why-nations-fail", title="Why Nations Fail",
             author_ids=["thinker-acemoglu"], year=2012, work_type=WorkType.BOOK,
             concepts_introduced=["concept-inclusive-vs-extractive"]),
        Work(id="work-capital-21st", title="Capital in the Twenty-First Century",
             author_ids=["thinker-piketty"], year=2013, work_type=WorkType.BOOK,
             concepts_introduced=["concept-r-greater-than-g"]),
        Work(id="work-great-stagnation", title="The Great Stagnation",
             author_ids=["thinker-cowen"], year=2011, work_type=WorkType.BOOK,
             concepts_introduced=["concept-great-stagnation"]),
        Work(id="work-nudge", title="Nudge",
             author_ids=["thinker-thaler", "thinker-sunstein"], year=2008, work_type=WorkType.BOOK),

        # ===== Contemporary Movements =====
        Work(id="work-rationality-ai-zombies", title="Rationality: From AI to Zombies",
             author_ids=["thinker-yudkowsky"], year=2015, work_type=WorkType.BOOK,
             tradition_ids=["tradition-rationalist-community"]),
        Work(id="work-meditations-moloch", title="Meditations on Moloch",
             author_ids=["thinker-scott-alexander"], year=2014, work_type=WorkType.ESSAY,
             tradition_ids=["tradition-rationalist-community"],
             concepts_introduced=["concept-moloch"]),
        Work(id="work-what-we-owe-future", title="What We Owe the Future",
             author_ids=["thinker-macaskill"], year=2022, work_type=WorkType.BOOK,
             tradition_ids=["tradition-ea"]),

        # ===== History =====
        Work(id="work-silk-roads", title="The Silk Roads: A New History of the World",
             author_ids=["thinker-frankopan"], year=2015, work_type=WorkType.BOOK,
             manuscript_refs=[ManuscriptReference(chapter=18, part="part3-metaphysics")]),

        # ===== Flow/Neuroscience =====
        Work(id="work-flow", title="Flow: The Psychology of Optimal Experience",
             author_ids=["thinker-csikszentmihalyi"], year=1990, work_type=WorkType.BOOK,
             concepts_introduced=["concept-flow-state"]),
        Work(id="work-forgetting-ourselves", title="Forgetting ourselves in flow: an active inference account of flow states",
             author_ids=["thinker-kotler"], year=2024, work_type=WorkType.PAPER,
             concepts_developed=["concept-flow-state", "concept-active-inference"]),

        # ===== Aesthetics =====
        Work(id="work-on-beauty", title="On Beauty and Being Just",
             author_ids=["thinker-scarry"], year=1999, work_type=WorkType.BOOK,
             manuscript_refs=[ManuscriptReference(chapter=23, part="part3-metaphysics")]),

        # ===== Comparative Religion =====
        Work(id="work-church-shadow-mosque", title="The Church in the Shadow of the Mosque",
             author_ids=["thinker-griffith"], year=2008, work_type=WorkType.BOOK,
             manuscript_refs=[ManuscriptReference(chapter=17, part="part3-metaphysics")]),
        Work(id="work-other-light-one", title="The Other in the Light of the One",
             author_ids=["thinker-shah-kazemi"], year=2006, work_type=WorkType.BOOK,
             manuscript_refs=[ManuscriptReference(chapter=17, part="part3-metaphysics")]),
    ]
